- include_role:
    name: nginx-server

- name: install system packages needed
  apt:
    name: "{{ item }}"
  with_items:
  - git
  - texlive-latex-base
  - texlive-latex-recommended
  - texlive-latex-extra
  - python-virtualenv
  become: yes

- include_role:
    name: cloned-repo
  vars:
    path: /home/dcraig/makewayforpiggies.huxleycraig.com
    repo: https://github.com/drcraig/make-way-for-piggies.git
    user: dcraig

- name: make the site
  make:
    chdir: /home/dcraig/makewayforpiggies.huxleycraig.com/
  become: yes
  become_user: dcraig

- include_role:
    name: nginx-config
  vars:
    root: /home/dcraig/makewayforpiggies.huxleycraig.com
    hostname: makewayforpiggies.localhost
