- name: initial bring up
  hosts: all
  tasks:
  - name: install aptitude
    apt: name=aptitude
    become: yes

  - name: "apt update && atp upgrade"
    apt: upgrade=yes update_cache=yes
    become: yes

  - name: change root password
    user:
      name: root
      password: "$6$xoQ7B8jzoa$Q18QxoMB/UabRzyCG.uVRjAUMR9TaGdMwzpFyv7vxpQ35.HvHa.mj9ICBuEKQRglhIE.eWictuB8RfYZq8lmb/"
    become: yes
