- include_role:
    name: nginx-server

- include_role:
    name: cloned-repo
  vars:
    path: /home/dcraig/hondacraig.com
    repo: https://github.com/drcraig/hondacraig.com.git
    user: dcraig

- include_role:
    name: nginx-config
  vars:
    root: /home/dcraig/hondacraig.com
    hostname: hondacraig.localhost
