- include_role:
    name: nginx-server

- name: create /home/dcraig/hondacraig.com
  file:
    path: /home/dcraig/hondacraig.com
    state: directory
    mode: 0755
  become: yes
  become_user: dcraig

- name: clone github repo
  git:
    repo: https://github.com/drcraig/hondacraig.com.git
    dest: /home/dcraig/hondacraig.com/
    update: yes
    accept_hostkey: yes
  become: yes
  become_user: dcraig

- name: nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/sites-enabled/hondacraig.com
  become: yes
  notify: reload nginx

