- include_role:
    name: nginx-server

- name: install system packages needed
  apt:
    name: "{{ item }}"
  with_items:
  - git
  - npm
  - nodejs-legacy
  - ruby-sass
  - python-virtualenv
  become: yes

- include_role:
    name: cloned-repo
  vars:
    path: /home/dcraig/dancraig.net
    repo: https://github.com/drcraig/dancraig.net.git
    user: dcraig

- name: npm install
  npm:
    path: /home/dcraig/dancraig.net/
    global: yes
  become: yes
  become_user: dcraig

- name: make the site
  make:
    chdir: /home/dcraig/dancraig.net/
  become: yes
  become_user: dcraig


- include_role:
    name: nginx-config
  vars:
    root: /home/dcraig/dancraig.net/app
    hostname: "{{ dancraig_hostname }}"
