- include_role:
    name: nginx-server

- name: install system packages needed
  apt:
    name: "{{ item }}"
  with_items:
  - git
  - npm
  - nodejs-legacy
  - ruby-sass
  - python-virtualenv
  become: yes

- include_role:
    name: cloned-repo
  vars:
    path: /home/dcraig/dancraig.net
    repo: https://github.com/drcraig/dancraig.net.git
    user: dcraig

- name: npm install
  npm:
    path: /home/dcraig/dancraig.net/
    global: yes
  become: yes

- name: npm install grunt
  npm:
    name: grunt-cli
    global: yes
  become: yes

- name: make the site
  make:
    chdir: /home/dcraig/dancraig.net/
  become: yes
  become_user: dcraig

- name: nginx config
  template:
    src: nginx.j2.conf
    dest: /etc/nginx/sites-enabled/dancraig.net
  become: yes
  notify: reload nginx
